# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: exome-seq-2.1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.8
  - fastp=0.20.1
  - picard=2.18.11
  - bwa=0.7.17
  - multiqc=1.9
  - samtools=1.9
  - bcftools=1.9
  - htslib=1.9 
  - perl-excel-writer-xlsx
  - r=3.5.1
  - r-base=3.5.1
  - ensembl-vep=99.2
