# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: metagenomics
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::openjdk=8.0.144 
 - fastqc=0.11.7
 - trim-galore=0.4.4
 - multiqc=1.5
 - bwa=0.7.15
 - samtools=1.5
 - gatk4=4.0.4.0
 - vcftools=0.1.15
