# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: exome-seq-3.1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.8
  - bioconda::fastp=0.20.1
  - bioconda::bwa-mem2=2.2.1
  - bioconda::bwa=0.7.17
  - bioconda::multiqc=1.11
  - bioconda::samtools=1.13
  - bioconda::bcftools=1.13
  - bioconda::htslib=1.13
  - perl-excel-writer-xlsx
  - bioconda::perl-json-parse=0.55
